In [27]:
import numpy as np

In [28]:
#slicing işlemlerinde sondaki dahil değildir.
arr = np.array([1, 2, 3])
print(arr)
print(f'type(arr): {type(arr)}', f'arr.shape: {arr.shape}', f'arr.ndim: {arr.ndim}', sep='\n')

[1 2 3]
type(arr): <class 'numpy.ndarray'>
arr.shape: (3,)
arr.ndim: 1


In [29]:
temp = arr[0]
print('temp: ', temp)
print(f'type(temp): {type(temp)}', f'temp.shape: {temp.shape}', f'temp.ndim: {temp.ndim}', sep='\n')

temp:  1
type(temp): <class 'numpy.int64'>
temp.shape: ()
temp.ndim: 0


In [31]:
temp = arr[0:1] # Bu işleme slicing denir ve hep dizi döner. Sondaki dahil değildir [0, 1)
print('temp: ', temp)
print(f'type(temp): {type(temp)}', f'temp.shape: {temp.shape}', f'temp.ndim: {temp.ndim}', sep='\n')
print('np.squeeze(temp): ', np.squeeze(temp)) # return 1. slicing' in verdiği dizi durumundan kurtarıyor

temp:  [1]
type(temp): <class 'numpy.ndarray'>
temp.shape: (1,)
temp.ndim: 1
np.squeeze(temp):  1


In [32]:
arr = np.array([
  [0, 1, 2],
  [3, 4, 5]
])
print(arr)
print(f'type(arr): {type(arr)}', f'arr.shape: {arr.shape}', f'arr.ndim: {arr.ndim}', sep='\n')

[[0 1 2]
 [3 4 5]]
type(arr): <class 'numpy.ndarray'>
arr.shape: (2, 3)
arr.ndim: 2


In [33]:
temp = arr[0:1]
print('temp: ', temp)
print(f'type(temp): {type(temp)}', f'temp.shape: {temp.shape}', f'temp.ndim: {temp.ndim}', sep='\n')
print('np.squeeze(temp): ', np.squeeze(temp))

temp:  [[0 1 2]]
type(temp): <class 'numpy.ndarray'>
temp.shape: (1, 3)
temp.ndim: 2
np.squeeze(temp):  [0 1 2]


In [34]:
temp = arr[:, 0]
print('temp: ', temp)
print(f'type(temp): {type(temp)}', f'temp.shape: {temp.shape}', f'temp.ndim: {temp.ndim}', sep='\n')
print('np.squeeze(temp): ', np.squeeze(temp))

temp:  [0 3]
type(temp): <class 'numpy.ndarray'>
temp.shape: (2,)
temp.ndim: 1
np.squeeze(temp):  [0 3]


In [38]:
temp = arr[:, 0:1] # dizi içinde dizi olursa her diziyi satır olarak görüyor
print('temp: ', temp)
print(f'type(temp): {type(temp)}', f'temp.shape: {temp.shape}', f'temp.ndim: {temp.ndim}', sep='\n')
print('np.squeeze(temp): ', np.squeeze(temp))

temp:  [[0]
 [3]]
type(temp): <class 'numpy.ndarray'>
temp.shape: (2, 1)
temp.ndim: 2
np.squeeze(temp):  [0 3]


In [39]:
arr = np.array([
  [
    [0, 1, 2],
    [3, 4, 5]
  ],
  [
    [4, 7, 8],
    [9, 10, 11]
  ]
])
print(arr)
print(f'type(arr): {type(arr)}', f'arr.shape: {arr.shape}', f'arr.ndim: {arr.ndim}', sep='\n')

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 4  7  8]
  [ 9 10 11]]]
type(arr): <class 'numpy.ndarray'>
arr.shape: (2, 2, 3)
arr.ndim: 3


In [40]:
temp = arr[0:1]
print('temp: ', temp)
print(f'type(temp): {type(temp)}', f'temp.shape: {temp.shape}', f'temp.ndim: {temp.ndim}', sep='\n')
print('np.squeeze(temp): ', np.squeeze(temp))

temp:  [[[0 1 2]
  [3 4 5]]]
type(temp): <class 'numpy.ndarray'>
temp.shape: (1, 2, 3)
temp.ndim: 3
np.squeeze(temp):  [[0 1 2]
 [3 4 5]]


In [41]:
temp = arr[:, 0]
print('temp: ', temp)
print(f'type(temp): {type(temp)}', f'temp.shape: {temp.shape}', f'temp.ndim: {temp.ndim}', sep='\n')
print('np.squeeze(temp): ', np.squeeze(temp))

temp:  [[0 1 2]
 [4 7 8]]
type(temp): <class 'numpy.ndarray'>
temp.shape: (2, 3)
temp.ndim: 2
np.squeeze(temp):  [[0 1 2]
 [4 7 8]]


In [42]:
temp = arr[:, 0:1] # dizi içinde dizi olursa her diziyi satır olarak görüyor
print('temp: ', temp)
print(f'type(temp): {type(temp)}', f'temp.shape: {temp.shape}', f'temp.ndim: {temp.ndim}', sep='\n')
print('np.squeeze(temp): ', np.squeeze(temp))

temp:  [[[0 1 2]]

 [[4 7 8]]]
type(temp): <class 'numpy.ndarray'>
temp.shape: (2, 1, 3)
temp.ndim: 3
np.squeeze(temp):  [[0 1 2]
 [4 7 8]]


In [43]:
temp = arr[:, :, 0:1]
print('temp: ', temp)
print(f'type(temp): {type(temp)}', f'temp.shape: {temp.shape}', f'temp.ndim: {temp.ndim}', sep='\n')
print('np.squeeze(temp): ', np.squeeze(temp))

temp:  [[[0]
  [3]]

 [[4]
  [9]]]
type(temp): <class 'numpy.ndarray'>
temp.shape: (2, 2, 1)
temp.ndim: 3
np.squeeze(temp):  [[0 3]
 [4 9]]
